# Generated by Django 4.2.24 on 2026-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='application_method',
            field=models.CharField(choices=[('job_board', 'Job board portal'), ('employer_website', 'Employer website'), ('email', 'Email application'), ('recruiter', 'Recruiter contact'), ('direct_contact', 'Direct company contact'), ('other', 'Other')], default='job_board', max_length=30),
        ),
    ]
