# Generated by Django 4.2.24 on 2026-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_application_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contact_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contact_person_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contact_phone_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
