# Generated by Django 4.2.24 on 2026-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_company_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
