# Generated by Django 4.2.24 on 2026-06-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('applications', '0004_alter_jobapplication_job_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anschreiben_text', models.TextField(blank=True)),
                ('email_text', models.TextField(blank=True)),
                ('match_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='applications.jobapplication')),
                ('selected_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_drafts', to='documents.userdocument')),
            ],
        ),
    ]
