# Generated by Django 4.2.24 on 2026-05-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='applicant_summary',
            field=models.TextField(blank=True, help_text='Short reusable profile summary for Anschreiben generation.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Deutschland', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_skills',
            field=models.TextField(blank=True, help_text='Reusable skills, technologies, languages, and strengths.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
