# Generated by Django 4.2.24 on 2026-05-09 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('cv', 'CV / Lebenslauf'), ('cover_letter', 'Cover Letter / Anschreiben'), ('certificate', 'Certificate / Zertifikat'), ('zeugnis', 'Zeugnis'), ('arbeitszeugnis', 'Arbeitszeugnis'), ('reference', 'Reference'), ('scan', 'Scanned Document'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=documents.models.user_document_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='applications.jobapplication')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_links', to='documents.userdocument')),
            ],
        ),
    ]
